/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData back = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData forward = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData star = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData star_half = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData community = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData heart = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData trending = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData logo = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData ticket = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData pin = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData play_circled = IconData(0xf144, fontFamily: _kFontFam);
}
