/// Flutter icons App
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  App
///      fonts:
///       - asset: fonts/App.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class App {
  App._();

  static const _kFontFam = 'App';

  static const IconData lofi_app_icons_search = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData lofi_icon_01 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData lofi_app_icons_profile = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData lofi_app_icons_ticket = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData lofi_app_icons_trending_trending = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData lofi_app_icons_community = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData lofi_app_icons_home = const IconData(0xe806, fontFamily: _kFontFam);
}
