service: lofi-api

frameworkVersion: ">=1.28.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  appName: lofi-api

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  memorySize: 128
  environment:
    REGION: ${self:provider.region}
  tags:
    appName: ${self:custom.appName}
    stage: ${self:custom.stage}
    owner: tony.truong

plugins:
  - serverless-offline
